blank_issues_enabled: true
contact_links:
  - name: General & Feature Requests
    url: https://github.com/inndevs/emoji-picker-macos-public/discussions/new?category=general-feature-requests
    about: Please use Discussions for feature requests so the community can vote and comment.
